# Generated by Django 2.0.3 on 2019-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='comment_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Gönderi'),
        ),
    ]
