# Generated by Django 2.0.3 on 2019-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190726_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='comment_number',
            field=models.IntegerField(null=True),
        ),
    ]
