# Generated by Django 2.0.3 on 2019-07-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20190725_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='city',
            field=models.CharField(max_length=30, verbose_name='city'),
        ),
    ]
